### ISSUE TITLE
Actions build creates CloudFormation template and pushes it to S3

### ISSUE THREAD

**Issue by JanneKataja-TomTom** [adhorn/chaos-ssm-documents#18]
Instead of needing to checkout the repo to create the CloudFormation template, it would be convenient to create the stack directly from S3 bucket URL. Create CloudFormation template in build pipeline and push it to S3 bucket on master branch code changes.

**Comment by adhorn** [comment]
Can you try that: https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/quickcreate?templateURL=https://chaos-ssm-documents.s3.amazonaws.com/cfn-chaos-ssm.yml&stackName=ChaosSsm

**Comment by jkataja** [comment]
Yes, the create link worked.

I have this create stacks array to launch Folding@Home stack in different regions: https://github.com/jkataja/cfn-foldingathome

| Region         | Create Stack              |
|----------------|---------------------------|
| US East (N. Virginia) `us-east-1` | [Launch Stack](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| US East (Ohio) `us-east-2` | [Launch Stack](https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| US West (N. California) `us-west-1`| [Launch Stack](https://us-west-1.console.aws.amazon.com/cloudformation/home?region=us-west-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
|US West (Oregon) `us-west-2` | [Launch Stack](https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Africa (Cape Town) `af-south-1`| [Launch Stack](https://af-south-1.console.aws.amazon.com/cloudformation/home?region=af-south-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Asia Pacific (Hong Kong) `ap-east-1`| [Launch Stack](https://ap-east-1.console.aws.amazon.com/cloudformation/home?region=ap-east-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Asia Pacific (Mumbai) `ap-south-1` | [Launch Stack](https://ap-south-1.console.aws.amazon.com/cloudformation/home?region=ap-south-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Asia Pacific (Seoul) `ap-northeast-2`| [Launch Stack](https://ap-northeast-2.console.aws.amazon.com/cloudformation/home?region=ap-northeast-2#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Asia Pacific (Singapore) `ap-southeast-1` | [Launch Stack](https://ap-southeast-1.console.aws.amazon.com/cloudformation/home?region=ap-southeast-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Asia Pacific (Sydney) `ap-southeast-2` | [Launch Stack](https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Asia Pacific (Tokyo) `ap-northeast-1` | [Launch Stack](https://ap-northeast-1.console.aws.amazon.com/cloudformation/home?region=ap-northeast-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Canada (Central) `ca-central-1` | [Launch Stack](https://ca-central-1.console.aws.amazon.com/cloudformation/home?region=ca-central-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
|Europe (Frankfurt) `eu-central-1` | [Launch Stack](https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Europe (Ireland) `eu-west-1` | [Launch Stack](https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Europe (London) `eu-west-2` | [Launch Stack](https://eu-west-2.console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Europe (Paris) `eu-west-3` | [Launch Stack](https://eu-west-3.console.aws.amazon.com/cloudformation/home?region=eu-west-3#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Europe (Stockholm) `eu-north-1`| [Launch Stack](https://eu-north-1.console.aws.amazon.com/cloudformation/home?region=eu-north-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| Middle East (Bahrain) `me-south-1` | [Launch Stack](https://me-south-1.console.aws.amazon.com/cloudformation/home?region=me-south-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |
| South America (São Paulo) `sa-east-1` | [Launch Stack](https://sa-east-1.console.aws.amazon.com/cloudformation/home?region=sa-east-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome) |

The URL are slightly different with **review** instead of **quickcreate** path:
```
https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://cfn-foldingathome.s3.amazonaws.com/foldingathome.yml&stackName=FoldingAtHome
```

**Comment by adhorn** [comment]
https://github.com/adhorn/chaos-ssm-documents/pull/19

**Comment by adhorn** [comment]
Thanks @jkataja  for the suggestions. [Readme](https://github.com/adhorn/chaos-ssm-documents/blob/master/README.rst) is now updated.

**Comment by JanneKataja-TomTom** [comment]
That was quick! And already should help in getting started faster. However, the create stack links table doesn't seem to format that well on GitHub.

**Comment by adhorn** [comment]
It was not supposed to be a table :)

**Comment by adhorn** [comment]
I made it pretty now :)

**Comment by JanneKataja-TomTom** [comment]
très beau

**Comment by adhorn** [comment]
Kitti :)
